# Generated by Django 3.1.2 on 2020-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_editor_platform_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="logo",
            field=models.ImageField(upload_to="logos"),
        ),
    ]
