# Generated by Django 3.1.5 on 2021-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('publication_pages', models.CharField(choices=[('COMM', 'Fiche commune'), ('DEPT', 'Fiche département'), ('REGION', 'Fiche région'), ('EPCI', 'Fiche EPCI'), ('HOME', 'Page principale'), ('SEARCH', 'Page de recherche')], max_length=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='home_url',
            field=models.URLField(null=True),
        ),
    ]
