# Generated by Django 3.1.5 on 2021-01-19 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20201104_1023'),
        ('core', '0004_auto_20210119_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('home_url', models.URLField(null=True)),
                ('editor', models.ManyToManyField(to='core.Editor')),
                ('rssfeed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.source')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='document',
            name='rss_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.post'),
        ),
        migrations.AddField(
            model_name='document',
            name='scope',
            field=models.ManyToManyField(to='core.Scope'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(to='core.Topic'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ManyToManyField(to='core.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source'),
        ),
        migrations.AddField(
            model_name='document',
            name='years',
            field=models.ManyToManyField(to='core.DataYear'),
        ),
    ]
