# Generated by Django 3.1.5 on 2021-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210119_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='icon',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='icon_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon_url',
            field=models.URLField(null=True),
        ),
    ]
