# Generated by Django 3.1.5 on 2021-01-19 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210119_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='home_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='source',
            name='scope',
            field=models.ManyToManyField(to='core.Scope'),
        ),
        migrations.AddField(
            model_name='source',
            name='topics',
            field=models.ManyToManyField(to='core.Topic'),
        ),
        migrations.AddField(
            model_name='source',
            name='years',
            field=models.ManyToManyField(to='core.DataYear'),
        ),
    ]
