# Generated by Django 3.1.5 on 2021-01-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20201104_1023'),
        ('core', '0007_auto_20210119_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='base_domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='base_domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='rssfeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.source', unique=True),
        ),
    ]
