# Generated by Django 3.1.5 on 2021-01-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20201104_1023'),
        ('core', '0008_auto_20210121_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rssfeed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.source'),
        ),
    ]
