# Generated by Django 3.1.5 on 2021-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210121_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='publication_pages',
        ),
        migrations.AddField(
            model_name='document',
            name='publication_pages',
            field=models.ManyToManyField(to='core.PageType'),
        ),
    ]
