# Generated by Django 3.1.5 on 2021-01-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20201104_1023'),
        ('francesubdivisions', '0008_remove_epci_insee'),
        ('core', '0014_auto_20210122_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='departements',
            field=models.ManyToManyField(blank=True, null=True, to='francesubdivisions.Departement', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ManyToManyField(blank=True, null=True, to='core.DocumentType', verbose_name='type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='est publié'),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_update',
            field=models.DateField(blank=True, null=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication_pages',
            field=models.ManyToManyField(blank=True, null=True, to='core.PageType', verbose_name='pages de publication'),
        ),
        migrations.AlterField(
            model_name='document',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='francesubdivisions.Region', verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rss_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.post', verbose_name='Post associé'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scope',
            field=models.ManyToManyField(blank=True, null=True, to='core.Scope', verbose_name='portée'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='core.Topic', verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='document',
            name='years',
            field=models.ManyToManyField(blank=True, null=True, to='core.DataYear'),
        ),
    ]
