# Generated by Django 3.1.5 on 2021-01-22 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210122_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='base_domain',
            field=models.CharField(max_length=100, null=True, verbose_name='domaine'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_update',
            field=models.DateField(default=datetime.date.today, verbose_name='dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='source',
            name='scope',
            field=models.ManyToManyField(to='core.Scope', verbose_name='portée'),
        ),
        migrations.AlterField(
            model_name='source',
            name='topics',
            field=models.ManyToManyField(to='core.Topic', verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='source',
            name='years',
            field=models.ManyToManyField(to='core.DataYear', verbose_name='année'),
        ),
    ]
