# Generated by Django 3.1.5 on 2021-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0008_remove_epci_insee'),
        ('core', '0017_auto_20210122_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='communes',
            field=models.ManyToManyField(blank=True, to='francesubdivisions.Commune', verbose_name='commune'),
        ),
        migrations.AddField(
            model_name='document',
            name='epcis',
            field=models.ManyToManyField(blank=True, to='francesubdivisions.Epci', verbose_name='EPCI'),
        ),
    ]
