# Generated by Django 3.1.5 on 2021-01-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210122_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='rssfeed',
            new_name='rss_feed',
        ),
    ]
