# Generated by Django 3.1.5 on 2021-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_source_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='document_type',
            field=models.ManyToManyField(blank=True, to='core.DocumentType', verbose_name='type de source'),
        ),
    ]
