# Generated by Django 3.1.5 on 2021-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210122_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ManyToManyField(blank=True, related_name='source_type', to='core.DocumentType', verbose_name='type de source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='document_type',
            field=models.ManyToManyField(blank=True, related_name='documents_type', to='core.DocumentType', verbose_name='type des documents inclus'),
        ),
    ]
