# Generated by Django 3.1.5 on 2021-01-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210122_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=512, unique=True, verbose_name='URL'),
        ),
    ]
