# Generated by Django 3.1.5 on 2021-01-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210122_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='prop',
            field=models.CharField(max_length=100, unique=True, verbose_name='propriété'),
        ),
    ]
