# Generated by Django 3.1.5 on 2021-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210122_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=100, verbose_name='sigle'),
        ),
    ]
