# Generated by Django 3.1.7 on 2021-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210225_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='icon_path',
            field=models.CharField(max_length=255, null=True, verbose_name='Chemin de l’icône'),
        ),
    ]
