# Generated by Django 3.2.5 on 2021-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francedata', '0001_initial'),
        ('core', '0039_auto_20210326_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='communes',
            field=models.ManyToManyField(blank=True, to='francedata.Commune', verbose_name='commune'),
        ),
        migrations.AlterField(
            model_name='document',
            name='departements',
            field=models.ManyToManyField(blank=True, to='francedata.Departement', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='document',
            name='epcis',
            field=models.ManyToManyField(blank=True, to='francedata.Epci', verbose_name='EPCI'),
        ),
        migrations.AlterField(
            model_name='document',
            name='regions',
            field=models.ManyToManyField(blank=True, to='francedata.Region', verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='source',
            name='communes',
            field=models.ManyToManyField(blank=True, to='francedata.Commune', verbose_name='commune'),
        ),
        migrations.AlterField(
            model_name='source',
            name='departements',
            field=models.ManyToManyField(blank=True, to='francedata.Departement', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='source',
            name='epcis',
            field=models.ManyToManyField(blank=True, to='francedata.Epci', verbose_name='EPCI'),
        ),
        migrations.AlterField(
            model_name='source',
            name='regions',
            field=models.ManyToManyField(blank=True, to='francedata.Region', verbose_name='région'),
        ),
    ]
