# Generated by Django 3.2.6 on 2021-08-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_squashed_0040_auto_20210722_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="icon_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chemin de l’icône"
            ),
        ),
    ]
