# Generated by Django 3.2.7 on 2021-09-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210827_1536"),
    ]

    operations = []
