# Generated by Django 3.2.8 on 2021-10-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_document_tags"),
    ]

    operations = []
