# Generated by Django 3.2.9 on 2021-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_document_bnsp_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['name'], 'verbose_name': 'type de territoire', 'verbose_name_plural': 'types de territoire'},
        ),
        migrations.AlterField(
            model_name='document',
            name='scope',
            field=models.ManyToManyField(blank=True, to='core.Scope', verbose_name='type de territoire'),
        ),
    ]
