# Generated by Django 3.2.9 on 2021-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20211104_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'publication'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name'], 'verbose_name': 'type de ressource', 'verbose_name_plural': 'types de ressource'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ManyToManyField(blank=True, to='core.DocumentType', verbose_name='type de ressource'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, to='core.Topic', verbose_name='thématique'),
        ),
        migrations.AlterField(
            model_name='source',
            name='document_type',
            field=models.ManyToManyField(blank=True, related_name='documents_type', to='core.DocumentType', verbose_name='type des publications inclus'),
        ),
    ]
