# Generated by Django 3.2.9 on 2021-11-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_document_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datayear',
            options={'get_latest_by': 'year', 'ordering': ['year'], 'verbose_name': 'millésime'},
        ),
    ]
