# Generated by Django 3.1.2 on 2020-11-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('insee', models.CharField(max_length=2)),
                ('siren', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('insee', models.CharField(max_length=2)),
                ('siren', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('insee', models.CharField(max_length=3)),
                ('siren', models.CharField(max_length=9)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.region')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('insee', models.CharField(max_length=5)),
                ('siren', models.CharField(max_length=9)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.departement')),
                ('epci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.epci')),
            ],
        ),
    ]
