# Generated by Django 3.1.2 on 2020-11-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('francesubdivisions', '0002_commune_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpciType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='epci',
            name='epci_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='francesubdivisions.epcitype'),
        ),
    ]
