# Generated by Django 3.2.8 on 2021-10-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_apis', '0002_alter_opendatasoftquery_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatasoftquery',
            name='identify_departements',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de départements'),
        ),
        migrations.AlterField(
            model_name='opendatasoftquery',
            name='identify_metropoles',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de métropoles'),
        ),
        migrations.AlterField(
            model_name='opendatasoftquery',
            name='identify_regions',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de régions'),
        ),
    ]
