# Generated by Django 3.2.8 on 2021-10-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_apis', '0004_bnspquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnspquery',
            options={'verbose_name': 'BNSP - requête'},
        ),
    ]
