# Generated by Django 3.2.8 on 2021-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_apis', '0005_alter_bnspquery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatasoftquery',
            name='identify_years',
            field=models.BooleanField(default=False, verbose_name='Identifier les années de publication'),
        ),
    ]
