# Generated by Django 3.2.6 on 2021-08-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0041_auto_20210827_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("query", models.CharField(max_length=255, verbose_name="requête")),
                (
                    "last_polled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière tentative"
                    ),
                ),
                (
                    "last_success",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière réussite"
                    ),
                ),
                (
                    "last_change",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier changement"
                    ),
                ),
                (
                    "live",
                    models.BooleanField(default=True, verbose_name="requête active"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.source",
                        verbose_name="source associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "requête",
            },
        ),
    ]
