# Generated by Django 3.2.7 on 2021-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=255, unique=True, verbose_name='requête'),
        ),
    ]
