# Generated by Django 3.2.7 on 2021-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnsp', '0002_auto_20210909_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=1000, unique=True, verbose_name='requête'),
        ),
    ]
