# Generated by Django 3.2.8 on 2021-10-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnsp', '0003_alter_query_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='live',
            new_name='is_active',
        ),
    ]
