# Generated by Django 3.2.8 on 2021-10-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnsp', '0005_auto_20211008_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='identify_departements',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de départements'),
        ),
        migrations.AddField(
            model_name='query',
            name='identify_main_cities',
            field=models.BooleanField(default=False, help_text='Ne marche que si la source possède des départements ou régions.', verbose_name='Identifier les noms des principales villes'),
        ),
        migrations.AddField(
            model_name='query',
            name='identify_metropoles',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de métropoles'),
        ),
        migrations.AddField(
            model_name='query',
            name='identify_regions',
            field=models.BooleanField(default=False, verbose_name='Identifier les noms de régions'),
        ),
    ]
