# Generated by Django 3.2.9 on 2021-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name': 'tableau', 'verbose_name_plural': 'tableaux'},
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='rank',
        ),
        migrations.AlterField(
            model_name='datatable',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='slug'),
        ),
    ]
