# Generated by Django 3.2.9 on 2021-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectivity_pages', '0003_vintage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectivitymessage',
            name='siren',
        ),
        migrations.AddField(
            model_name='collectivitymessage',
            name='collectivity_slug',
            field=models.CharField(default='paris', max_length=50, verbose_name='slug collectivité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datarow',
            name='key',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
    ]
