# Generated by Django 3.2.7 on 2021-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date d’import'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='import effectué'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='public_label',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='libellé public'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
