# Generated by Django 3.2.14 on 2023-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francedata', '0004_alter_datayear_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldatamapping',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical table de correspondance', 'verbose_name_plural': 'historical tables de correspondance'},
        ),
        migrations.AlterField(
            model_name='historicaldatamapping',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
