# Generated by Django 3.2.13 on 2023-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francedata', '0005_auto_20230111_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldatamapping',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical table de correspondance'},
        ),
        migrations.AlterField(
            model_name='historicaldatamapping',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
